/* eslint-disable camelcase, import/no-cycle */
import IUser from "./IUser";

export default interface IPreviousOutsideProject {
  id: number; // primary key
  student: IUser;
  status: string; // auto-generated
  title: string;
  category: string;
  start_date: string;
  end_date: string;
  role: string;
  external_link: string;
  client: string;
  description: string;
  skills: string[];
  tools: string[];
  photos_url: string[];

  updated: string; // auto-generated
}

export const previousOutsideProjectRequiredCols = ["student", "title"];
export const previousOutsideProjectAutoGeneratedCols = ["status"];
