/* eslint-disable camelcase, import/no-cycle */
import IBusiness from "./IBusiness";
import IProjectMilestone from "./IProjectMilestone";
import IUser from "./IUser";

export default interface IProject {
  id: number; // auto-generated
  title: string;
  description: string;
  project_type: string; // auto-generated
  status: string; // auto-generated

  business: IBusiness;
  employee: IUser;
  student: IUser;

  required_skills: string[];
  duration: number; // auto-generated
  stipend: number;
  start_date: string;
  due_date: string;
  stream: string;
  project_detail: string[];
  hourly_price: number;
  location: string;
  payment_type: string;
  remote: boolean;
  milestones: IProjectMilestone[];
  applicants: number; // auto-generated
  image: string;
  introduction: string;
  industry: string;
  role: string;
  created_by: string;

  updated: string; // auto-generated
}

export const projectRequiredCols = [
  "title",
  "description",
  "business",
  "stipend",
  "start_date",
  "due_date",
  "stream",
  "project_detail",
  "hourly_price",
  "location",
  "payment_type",
  "remote",
];
export const projectAutoGeneratedCols = [
  "project_type",
  "status",
  "duration",
  "applicants",
];
