/* eslint-disable camelcase, import/no-cycle */
import IProject from "./IProject";
import IUser from "./IUser";

export default interface IProjectApplication {
  message: string;
  project: IProject;
  student: IUser;
  date: string;
  desired_pay: string;
  headline: string;
  skills: string[];
  role: string;
  resume_url: string;
  preference: string[];
  profile_picture_url: string;
  location: string;
  name: string;
  status: string;
}

export const projectApplicationRequiredCols = [];
export const projectApplicationAutoGeneratedCols = ["project"];
