/* eslint-disable import/no-cycle */
/* eslint-disable camelcase */
import IProject from "./IProject";
import IUser from "./IUser";

export default interface IProjectMilestone {
  id: number;
  name: string;
  task: string;
  isCompleted: boolean;
  hours: number;
  startDate: string;
  endDate: string;
  project: IProject;
  student: IUser;

  updated: string; // auto-generated
}

export const projectMilestoneRequiredCols = [
  "name",
  "task",
  "hours",
  "startDate",
  "endDate",
];
export const projectMilestoneAutoGeneratedCols = ["isCompleted"];
