/* eslint-disable camelcase, import/no-cycle */
import IApplication from "./IProjectApplication";
import IBusiness from "./IBusiness";
import IEducation from "./IEducation";
import IRoom from "./IRoom";
import IMessage from "./IMessage";
import IPreviousOutsideProject from "./IPreviousOutsideProject";
import IProject from "./IProject";
import IWorkExperience from "./IWorkExperience";
import IReview from "./IReview";
import IProjectMilestone from "./IProjectMilestone";

export default interface IUser {
  id: number; // auto-generated
  email: string;
  hash: string;
  salt: string;
  first_name: string;
  last_name: string;
  mobile_number: string;
  status: string;

  about_me: string;
  gender: string;
  headline: string;
  profile_picture_url: string;
  profile_video_url: string;
  resume_url: string;
  location: string;
  role: string;
  external_urls: string;
  desired_pay: string;

  type: string;
  skills: string[];
  preferences: string[];
  certifications: string[];
  others: string;
  business: IBusiness;
  projects: IProject[];
  education: IEducation[];
  work_experiences: IWorkExperience[];
  previous_outside_projects: IPreviousOutsideProject[];
  applications: IApplication[];
  reviews: IReview[];
  rooms: IRoom[];
  messages: IMessage[];
  milestones: IProjectMilestone[];

  stripeId: string;
  chatkittyId: number;
  updated: string;
}

export const userRequiredCols = [
  "email",
  "password",
  "first_name",
  "last_name",
];
export const userAutoGeneratedCols = ["hash", "salt", "type"];
