/* eslint-disable camelcase */
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  UpdateDateColumn,
} from "typeorm";
import isNullGenerator from "../utils/isNullGenerator";
import IProjectApplication, {
  projectApplicationRequiredCols,
  projectApplicationAutoGeneratedCols,
} from "./IProjectApplication";
import IProject from "./IProject";
import IUser from "./IUser";

const isNullable = isNullGenerator(
  projectApplicationRequiredCols,
  projectApplicationAutoGeneratedCols
);

@Entity()
export default class ProjectApplication implements IProjectApplication {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ nullable: isNullable("message") })
  message!: string;

  @ManyToOne("Project", "applications")
  project!: IProject;

  @ManyToOne("Student", "applications")
  student!: IUser;

  @Column({ nullable: isNullable("date") })
  date!: string;

  @Column({ nullable: isNullable("desired_pay") })
  desired_pay!: string;

  @Column({ nullable: isNullable("headline") })
  headline!: string;

  @Column("text", { array: true, default: {} })
  skills!: string[];

  @Column({ nullable: isNullable("role") })
  role!: string;

  @Column({ nullable: isNullable("resume_url") })
  resume_url!: string;

  @Column("text", { array: true, default: {} })
  preference!: string[];

  @Column({ nullable: isNullable("profile_picture_url") })
  profile_picture_url!: string;

  @Column({ nullable: isNullable("location") })
  location!: string;

  @Column({ nullable: isNullable("name") })
  name!: string;

  @Column({ nullable: isNullable("status") })
  status!: string;

  @UpdateDateColumn()
  updated!: string;
}
