/* eslint-disable camelcase */
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
} from "typeorm";
import IUser, { userAutoGeneratedCols, userRequiredCols } from "./IUser";
import IBusiness from "./IBusiness";
import IProject from "./IProject";
import IPreviousOutsideProject from "./IPreviousOutsideProject";
import IEducation from "./IEducation";
import IWorkExperience from "./IWorkExperience";
import isNullGenerator from "../utils/isNullGenerator";

const isNullable = isNullGenerator(userRequiredCols, userAutoGeneratedCols);

@Entity()
export default class User implements IUser {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ unique: true, nullable: isNullable("email") })
  email!: string;

  @Column({ nullable: isNullable("hash") })
  hash!: string;

  @Column({ nullable: isNullable("salt") })
  salt!: string;

  @Column({ nullable: isNullable("first_name") })
  first_name!: string;

  @Column({ nullable: isNullable("last_name") })
  last_name!: string;

  @Column({ nullable: isNullable("mobile_number") })
  mobile_number!: string;

  @Column({ nullable: isNullable("status") })
  status!: string;

  @Column({ nullable: isNullable("about_me") })
  about_me!: string;

  @Column({ nullable: isNullable("about_me") })
  headline!: string;

  @Column({ nullable: isNullable("profile_picture_url") })
  profile_picture_url!: string;

  @Column({ nullable: isNullable("resume_url") })
  resume_url!: string;

  @Column({ nullable: isNullable("location") })
  location!: string;

  @Column({ nullable: isNullable("role") })
  role!: string;

  @Column("text", { array: false, nullable: isNullable("external_urls") })
  external_urls!: string;

  @Column("text", { default: "student", nullable: isNullable("type") })
  type!: string;

  @Column("text", { array: true, default: {} })
  skills!: string[];

  @Column("text", { array: true, default: {} })
  preferences!: string[];

  @Column("json", { default: [] })
  certifications!: string[];
  
  @Column("json", { default: [] })
  others!: string[];

  @ManyToOne("Business", "employees")
  business!: IBusiness;

  @OneToMany("Project", "student")
  projects!: IProject[];

  @OneToMany("Education", "student")
  education!: IEducation[];

  @OneToMany("WorkExperience", "student")
  work_experiences!: IWorkExperience[];

  @OneToMany("PreviousOutsideProject", "student")
  previous_outside_projects!: IPreviousOutsideProject[];

  @Column({ nullable: isNullable("stripeId") })
  stripeId!: string;

  @UpdateDateColumn()
  updated!: string;
}
