name: Deploy backend main to AWS EB Dev
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%b-%d-%H-%M')"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: ant-backend
          environment_name: backend-dev
          version_label: ${{ steps.date.outputs.date }}
          region: us-east-2
          deployment_package: deploy.zip
          use_existing_version_if_available: false
# https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
