export default function isNullGenerator(
  requiredCols: string[],
  autoGeneratedCols?: string[]
) {
  return (prop: string): boolean => {
    if (autoGeneratedCols) {
      return !requiredCols.includes(prop) && !autoGeneratedCols.includes(prop);
    }
    return !requiredCols.includes(prop);
  };
}
