---
openapi: 3.0.0
info:
    version: 1.0.0
    title: Project ANT Backend
servers:
    - url: projectant.io
paths:
    "/users/{user_id}":
        get:
            summary: Details about a user
            description: Returns the record of a user based on their ID.
            operationId: getUser
            tags:
                - user
            parameters:
                - name: user_id
                in: path
                description: ID of the user
                required: true
                schema:
                type: string
            responses:
                "200":
                    description: Details about a user
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                "403":
                    description: Permissions error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
components:
    schemas:
        User:
            type: object
            required:
                - id
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                tag:
                    type: string
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                    format: int32
                message:
                    type: string
